#!/bin/bash

echo "=== Guide de Test du Système de Quiz de Module ==="
echo ""
echo "🚀 Serveur Laravel démarré sur http://localhost:8000"
echo ""
echo "📋 Étapes de test à suivre :"
echo ""
echo "1. 🔐 CONNEXION"
echo "   - Allez sur http://localhost:8000"
echo "   - Connectez-vous en tant que formateur"
echo ""
echo "2. 📚 NAVIGATION"
echo "   - Allez dans 'Mes Cours'"
echo "   - Sélectionnez un cours existant"
echo "   - Cliquez sur un module"
echo ""
echo "3. ➕ CRÉATION DE QUIZ"
echo "   - Si le module n'a pas de quiz, vous verrez 'Ajouter le quiz'"
echo "   - Cliquez sur ce bouton"
echo "   - Créez un quiz avec au moins 2 questions"
echo "   - Soumettez le formulaire"
echo ""
echo "4. ✅ VÉRIFICATIONS"
echo "   - Le bouton 'Ajouter le quiz' devrait avoir disparu"
echo "   - Le quiz devrait apparaître en dernier après les leçons"
echo "   - Fond orange avec l'icône clipboard-check"
echo "   - Badge 'QUIZ DE MODULE' visible"
echo "   - Boutons d'édition et suppression présents"
echo ""
echo "5. 🔄 TESTS SUPPLÉMENTAIRES"
echo "   - Cliquez sur 'Modifier' pour éditer le quiz"
echo "   - Essayez de créer un autre quiz (devrait être impossible)"
echo "   - Testez la suppression du quiz"
echo ""
echo "6. 🎓 TEST APPRENANT"
echo "   - Connectez-vous en tant qu'apprenant"
echo "   - Suivez les leçons du module"
echo "   - Le quiz devrait apparaître à la fin"
echo ""
echo "🎯 Points clés à vérifier :"
echo "   ✓ Un seul quiz par module maximum"
echo "   ✓ Quiz affiché après toutes les leçons"
echo "   ✓ Style visuel distinctif (orange)"
echo "   ✓ Badge et icône spéciaux"
echo "   ✓ Bouton conditionnel qui disparaît"
echo "   ✓ Fonctionnalités CRUD complètes"
echo ""
echo "🐛 En cas de problème :"
echo "   - Vérifiez les logs Laravel : tail -f storage/logs/laravel.log"
echo "   - Ouvrez la console développeur du navigateur"
echo "   - Consultez le fichier QUIZ_MODULE_IMPLEMENTATION_FINAL.md"
echo ""
echo "=== Test terminé ! ==="
